<!DOCTYPE html>
<html>
<head>
	<title>Aplicación Informática LabSis MM Fisher'st</title>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />	
	<link rel="stylesheet" href="public/css/index.css">
</head>
<body ng-controller='ApplicationControllers'>
	<div class="app" id="app" ng-class="{'app-header-fixed':app.settings.headerFixed, 'app-aside-fixed':app.settings.asideFixed, 'app-aside-folded':app.settings.asideFolded, 'app-aside-dock':app.settings.asideDock, 'container':app.settings.container}" ui-view></div>

	<script src="public/vendors/jquery.min.js"></script>
	<script src="public/vendors/jquery-ui.js"></script>	
  <script type="application/javascript" src='public/app.js'></script>
	<!--<script type="application/javascript" src='public/dist/js/main.build.js'></script>-->
</body>
</html>