<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Envio de correo correcto</title>
    <link rel="stylesheet" href="{{base_url()}}/public/css/index.css" type="text/css">
  </head>
  <body>
    <div class="app ng-scope app-header-fixed app-aside-fixed">
      <div class="modal-over bg-black ng-scope">
        <div class="modal-center animated fadeInUp text-center" style="width:200px;margin:-100px 0 0 -100px;">
          <h2 style='font-size:8em;'>
            <i class="icon-like"></i>
          </h2>
          <p class="h4 m-t m-b">Hemos enviado con exito la solicitud</p>
          <div class="input-group">
            <span class="input-group-btn">
              <a href="{{ base_url() }}" class="btn btn-lg btn-success btn-rounded no-border"><i class="fa fa-arrow-right"></i></a>
            </span>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
